### ISSUE TITLE
Failed to connect to internet when app in background

### ISSUE THREAD

**Issue by umesh0492** [TakahikoKawasaki/nv-websocket-client#111]
Failed to connect to 'frainz.com:80': failed to connect to frainz.com (port 80) after 10000ms
                                                                         com.neovisionaries.ws.client.WebSocketException: Failed to connect to 'frainz.com:80': failed to connect to frainz.com (port 80) after 10000ms
                                                                             at com.neovisionaries.ws.client.SocketConnector.NL(SocketConnector.java:127)
                                                                             at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:82)
                                                                             at com.neovisionaries.ws.client.WebSocket.NU(WebSocket.java:2139)
                                                                             at com.frainz.android.service.MessageService.BK(MessageService.java:373)
                                                                             at com.frainz.android.service.MessageService.b(MessageService.java:267)
                                                                             at com.frainz.android.service.MessageService$$Lambda$1.run(Unknown Source)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.net.SocketTimeoutException: failed to connect to frainz.com (port 80) after 10000ms
                                                                             at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                             at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                             at java.net.Socket.connect(Socket.java:884)
                                                                             at com.neovisionaries.ws.client.SocketConnector.NL(SocketConnector.java:111)
                                                                             at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:82) 
                                                                             at com.neovisionaries.ws.client.WebSocket.NU(WebSocket.java:2139) 
                                                                             at com.frainz.android.service.MessageService.BK(MessageService.java:373) 
                                                                             at com.frainz.android.service.MessageService.b(MessageService.java:267) 
                                                                             at com.frainz.android.service.MessageService$$Lambda$1.run(Unknown Source) 
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by umesh0492** [comment]
This happens only if the app is in the background, once you open the app it get connected.

**Comment by umesh0492** [comment]
need to handle doze mode and app standby after marshmallow.
@TakahikoKawasaki

**Comment by eku** [comment]
@umesh0492 nv-websocket-client is a generic Websocket framework. Android specific problems can be solved by you outside this framework.

**Comment by dbrgn** [comment]
I'm also having this issue. Probably Android is preventing sockets from being opened if the app is in background.

@umesh0492 did you find a solution?
