### ISSUE TITLE
ReadingThreadCloseTimer task hanging after disconnect

### ISSUE THREAD

**Issue by jleskovar** [TakahikoKawasaki/nv-websocket-client#140]
Something I've noticed quite frequently when attempting to `disconnect()` on a web socket. The ReadingThreadCloseTimer task spuriously fails to cancel, resulting in the following task preventing JVM shutdown (see stack dump below):

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode):

"DestroyJavaVM" #13 prio=5 os_prio=31 tid=0x00007fdb8d9d5800 nid=0x1a03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"ReadingThreadCloseTimer" #12 prio=5 os_prio=31 tid=0x00007fdb8d1c4800 nid=0x4f07 in Object.wait() [0x000070000bdb5000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000079568e1e8> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x000000079568e1e8> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Monitor Ctrl-Break" #9 daemon prio=5 os_prio=31 tid=0x00007fdb8c91a000 nid=0x4d03 runnable [0x000070000bcb2000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000007958ea2c0> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000007958ea2c0> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:84)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #8 daemon prio=9 os_prio=31 tid=0x00007fdb8c865800 nid=0x4903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fdb8d02d000 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fdb8d01c800 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fdb8e021000 nid=0x4303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fdb8e000000 nid=0x4103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fdb8c80f800 nid=0x3103 in Object.wait() [0x000070000b59d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000797608e40> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x0000000797608e40> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fdb8e009000 nid=0x2f03 in Object.wait() [0x000070000b49a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000797608ff8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000797608ff8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x00007fdb8d84a000 nid=0x2d03 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fdb8d80b000 nid=0x2503 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fdb8d80b800 nid=0x2703 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fdb8d80c800 nid=0x2903 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fdb8d80d000 nid=0x2b03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fdb8e020800 nid=0x4b03 waiting on condition 

JNI global references: 252

Heap
 PSYoungGen      total 38400K, used 8941K [0x0000000795580000, 0x0000000798000000, 0x00000007c0000000)
  eden space 33280K, 11% used [0x0000000795580000,0x000000079593d3e0,0x0000000797600000)
  from space 5120K, 99% used [0x0000000797600000,0x0000000797afe160,0x0000000797b00000)
  to   space 5120K, 0% used [0x0000000797b00000,0x0000000797b00000,0x0000000798000000)
 ParOldGen       total 87552K, used 1792K [0x0000000740000000, 0x0000000745580000, 0x0000000795580000)
  object space 87552K, 2% used [0x0000000740000000,0x00000007401c03e8,0x0000000745580000)
 Metaspace       used 12609K, capacity 12768K, committed 13056K, reserved 1060864K
  class space    used 1350K, capacity 1440K, committed 1536K, reserved 1048576K
```

The socket itself does seem to be disconnected though, so not sure what is going on. Perhaps the timer thread should be declared as daemon to allow the JVM to shutdown cleanly?

**Comment by MinnDevelopment** [comment]
Try using `webSocket.sendClose(1000)` instead.
