### ISSUE TITLE
WebSocketFactory.createSocket causes an exception on Android

### ISSUE THREAD

**Issue by or-else** [TakahikoKawasaki/nv-websocket-client#35]
Here is the stack:

  at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
  at java.net.InetAddress.getByName(InetAddress.java:305)
  at java.net.InetSocketAddress.<init>(InetSocketAddress.java:100)
  at java.net.InetSocketAddress.<init>(InetSocketAddress.java:85)
  at com.neovisionaries.ws.client.WebSocketFactory.createDirectRawSocket(WebSocketFactory.java:621)
  at com.neovisionaries.ws.client.WebSocketFactory.createRawSocket(WebSocketFactory.java:577)
  at com.neovisionaries.ws.client.WebSocketFactory.createSocket(WebSocketFactory.java:509)
  at com.neovisionaries.ws.client.WebSocketFactory.createSocket(WebSocketFactory.java:488)

Specifically the WebSocketFactory.java:621: `SocketAddress address = new InetSocketAddress(host, port);` which causes a network call. It kind of defeats the purpose of having `connectAsynchronously`.

The fix seems to be easy. Instead of WebSocketFactory.java:621

        // The address to connect to.
        SocketAddress address = new InetSocketAddress(host, port);

        // Create an instance that will execute the task to connect to the server later.
        return new SocketConnector(socket, address, timeout);

do 

        // Create an instance that will execute the task to connect to the server later.
        return new SocketConnector(socket, host, port, timeout);

Then have SocketConnector call  `new InetSocketAddress(host, port);` on the first call to `connect()`.

**Comment by TakahikoKawasaki** [comment]
Thank you for your nice report. I've fixed the problem and released a new version `1.22` including the fix. (The issue could have been found soon if I had tried it on Android. Sorry.)

**Comment by or-else** [comment]
Just verified on Android API 23. Confirming that it's fixed now. Thanks!
