### ISSUE TITLE
Deadlock when sending some data in onConnected event

### ISSUE THREAD

**Issue by avasenin** [TakahikoKawasaki/nv-websocket-client#43]
Stack traces:

```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at com.neovisionaries.ws.client.WritingThread.queueFrame(WritingThread.java:191)
	  at com.neovisionaries.ws.client.WebSocket.sendFrame(WebSocket.java:1918)
	  at com.neovisionaries.ws.client.WebSocket.sendText(WebSocket.java:2106)


"ReadingThread@2526" prio=5 tid=0x15 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks WritingThread@2528
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at com.neovisionaries.ws.client.WritingThread.queueFrame(WritingThread.java:191)
	  at com.neovisionaries.ws.client.WebSocket.sendFrame(WebSocket.java:1918)
	  at com.neovisionaries.ws.client.WebSocket.sendText(WebSocket.java:2106)
	  ...
	  at com.neovisionaries.ws.client.ListenerManager.callOnConnected(ListenerManager.java:189)
	  at com.neovisionaries.ws.client.WebSocket.callOnConnectedIfNotYet(WebSocket.java:3207)
	  at com.neovisionaries.ws.client.WebSocket.onReadingThreadStarted(WebSocket.java:3152)

"WritingThread@2528" prio=5 tid=0x16 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for ReadingThread@2526 to release lock on <0x9e5> (a java.lang.Object)
	  at com.neovisionaries.ws.client.WebSocket.onWritingThreadStarted(WebSocket.java:3173)
	  at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:82)
	  at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:56)
```

**Comment by TakahikoKawasaki** [comment]
Are you using the latest version (1.22)?

**Comment by avasenin** [comment]
This one was caused on 1.16. Did you change something?

**Comment by TakahikoKawasaki** [comment]
1.16 was the version where I fixed a deadlock bug. Hmm... I must investigate the issue. Thank you for your report.

**Comment by avasenin** [comment]
Deadlock in 1.16 was reported by me in https://github.com/TakahikoKawasaki/nv-websocket-client/issues/43. It's definitely another issue.
  
Seems that I found the reason of this. In my case I'm sending a lot of data in onConnected callback. I'm using your library with congestion control enables. It means that frame queue size is limited. Deadlock happens If the number of messages submitted in onConnected callback > frame queue size and onConnected callback is triggered by ReadingThread. The reason of this in `synchronized (mThreadsLock)` which doesn't allow to start WritingThread.  ReadingThread waits until WritingThread get items from frame queue and WritingThread waits when ReadingThread unlock mThreadsLock mutex because it's not started. Deadlock

**Comment by avasenin** [comment]
@TakahikoKawasaki Could you provide any ETA? Sorry for pushing this but I'm under pressure with this ticket and if it takes some time to fix on websocket-library level then I will implement a workaround on application level.

**Comment by TakahikoKawasaki** [comment]
Sorry, I'll look into the issue. Probably, I'll be able to update the code soon.

**Comment by TakahikoKawasaki** [comment]
@avasenin Try the new version, 1.23. If the issue still happens even with the new version, let me know again.

**Comment by avasenin** [comment]
Thx, I will check it tomorrow.

**Comment by avasenin** [comment]
Works great. Thanks

**Comment by eku** [comment]
@TakahikoKawasaki I'm wondering why you don't use https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html? Would drop the need of ```synchronized```.
