### ISSUE TITLE
its crashing

### ISSUE THREAD

**Issue by umesh0492** [TakahikoKawasaki/nv-websocket-client#62]
Non-fatal Exception: com.neovisionaries.ws.client.WebSocketException: Flushing frames to the server failed: sendto failed: EPIPE (Broken pipe)
       at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:436)
       at com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:386)
       at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:110)
       at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:57)
Caused by java.net.SocketException: sendto failed: EPIPE (Broken pipe)
       at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
       at libcore.io.IoBridge.sendto(IoBridge.java:515)
       at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
       at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
       at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
       at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
       at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
       at java.io.FilterOutputStream.flush(FilterOutputStream.java:88)
       at com.neovisionaries.ws.client.WritingThread.flush(WritingThread.java:273)
       at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:424)
       at com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:386)
       at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:110)
       at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:57)
Caused by android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
       at libcore.io.Posix.sendtoBytes(Posix.java)
       at libcore.io.Posix.sendto(Posix.java:206)
       at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
       at libcore.io.IoBridge.sendto(IoBridge.java:513)
       at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
       at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
       at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
       at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
       at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
       at java.io.FilterOutputStream.flush(FilterOutputStream.java:88)
       at com.neovisionaries.ws.client.WritingThread.flush(WritingThread.java:273)
       at com.neovisionaries.ws.client.WritingThread.doFlush(WritingThread.java:424)
       at com.neovisionaries.ws.client.WritingThread.sendFrames(WritingThread.java:386)
       at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:110)
       at com.neovisionaries.ws.client.WritingThread.run(WritingThread.java:57)

**Comment by afarber** [comment]
Are you going to just dump your errors here or will you provide more context, like source code you have used?

**Comment by TakahikoKawasaki** [comment]
@umesh0492 
`EPIPE` is an error code defined in `errno.h`.

http://man7.org/linux/man-pages/man3/errno.3.html

Error codes defined in `errno.h` are used by system calls (= functions exposed by Operation System) and some C libraries.

When you see `E????` such as `EPIPE` and `EIO`, it indicates something wrong in a lower layer has happened and it is not a problem in WebSocket library layer.
