### ISSUE TITLE
Getting WebSocketException on Android API below 20 but not higher

### ISSUE THREAD

**Issue by jerrymg** [TakahikoKawasaki/nv-websocket-client#84]
I get the following exception only on  API below 20 but not higher.

Here is the code
```
connection = new WebSocketFactory()
                        .createSocket(wssURLString)
                        .addListener(new WebSocketAdapter() {
...
connection.connect();
```
Here is the exception

```
W/System.err: com.neovisionaries.ws.client.WebSocketException: Failed to get the input stream of the raw socket: Connection closed by peer
W/System.err:     at com.neovisionaries.ws.client.WebSocket.openInputStream(WebSocket.java:3013)
W/System.err:     at com.neovisionaries.ws.client.WebSocket.shakeHands(WebSocket.java:2971)
W/System.err:     at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2025)
...
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err: Caused by: javax.net.ssl.SSLException: Connection closed by peer
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:661)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:632)
W/System.err:     at com.neovisionaries.ws.client.WebSocket.openInputStream(WebSocket.java:3006)
W/System.err: 	... 10 more
```

**Comment by TakahikoKawasaki** [comment]
This is just a guess, but I'm afraid that the default TLS version on the older platforms (below 20) is rejected by the server. #69 may give you a hint.

**Comment by jerrymg** [comment]
I think your right, it is a TLS version issue, but when I tried to force TLSv1.2 with `NaiveSSLContext.getInstance` below or disabled SSL3 with `NoSSLv3SocketFactory` below I still get the same `WebSocketException` exception mentioned above. Do you know what I’m doing wrong?


I tried your class `NaiveSSLContext` with
```
WebSocketFactory factory = new WebSocketFactory();
factory.setSSLContext(NaiveSSLContext.getInstance("TLSv1.2"));
connection = factory
                        .createSocket(“wss://www.arcbit.net:443/inv”)
                        .addListener(new WebSocketAdapter() {
...
connection.connect();
```


And I also tried 
```
WebSocketFactory factory = new WebSocketFactory();
factory.setSSLSocketFactory(new NoSSLv3SocketFactory());
connection = factory
                        .createSocket(“wss://www.arcbit.net:443/inv”)
                        .addListener(new WebSocketAdapter() {

```
Where `NoSSLv3SocketFactory` came from https://github.com/Rap-ID/Rap-ID-Android/blob/master/app/src/main/java/com/hackerchai/rapid/Thread/NoSSLv3SocketFactory.java
