### ISSUE TITLE
Timer was canceled

### ISSUE THREAD

**Issue by matteosist** [TakahikoKawasaki/nv-websocket-client#86]
Hi, to begin thanks for this awesome library.
I'm writing you because today i have got this crash from your lib.
Can you help me?

`Fatal Exception: java.lang.IllegalStateException: Timer was canceled
       at java.util.Timer.scheduleImpl(Timer.java:558)
       at java.util.Timer.schedule(Timer.java:456)
       at com.neovisionaries.ws.client.PeriodicalFrameSender.doTask(PeriodicalFrameSender.java:154)
       at com.neovisionaries.ws.client.PeriodicalFrameSender.access$100(PeriodicalFrameSender.java:23)
       at com.neovisionaries.ws.client.PeriodicalFrameSender$Task.run(PeriodicalFrameSender.java:133)
       at java.util.Timer$TimerImpl.run(Timer.java:284)`

More info:
Device: SM-G935F
OS: 6.0.1

Thank you.

**Comment by TakahikoKawasaki** [comment]
Thank you for your report. The case should be treated properly. I'll update the library.

**Comment by TakahikoKawasaki** [comment]
@matteosist Released version 1.31 including a patch for this issue.

**Comment by TakahikoKawasaki** [comment]
I think that the version 1.31 has resolved this issue. Reopen this issue if necessary.
